CREATE TABLE country (
  country_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE city (
  city_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id integer NOT NULL,
  name varchar(100) NOT NULL
);

CREATE TABLE app_user (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(100) NOT NULL,
  last_name varchar(100),
  email varchar(255) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  birth_date date,
  gender varchar(20),
  country_id integer,
  city_id integer,
  avatar varchar(500),
  rating decimal(5,2) DEFAULT 0,
  registration_date timestamp DEFAULT (CURRENT_TIMESTAMP),
  last_login timestamp
);

CREATE TABLE person (
  person_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(100) NOT NULL,
  last_name varchar(100),
  middle_name varchar(100),
  birth_date date,
  birth_place varchar(255),
  country_id integer,
  city_id integer,
  biography text,
  education text,
  photo varchar(500),
  created_at timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE person_role (
  person_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id integer NOT NULL,
  role varchar(100) NOT NULL
);

CREATE TABLE genre (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  description text
);

CREATE TABLE film (
  film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(500) NOT NULL,
  description text,
  created_date date,
  age_restriction varchar(10),
  average_rating decimal(3,2) DEFAULT 0,
  added_at timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE film_genre (
  film_genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer NOT NULL,
  genre_id integer NOT NULL
);

CREATE TABLE film_person (
  film_person_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer NOT NULL,
  person_id integer NOT NULL,
  role varchar(100) NOT NULL
);

CREATE TABLE user_device (
  device_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  type varchar(50) NOT NULL,
  model varchar(255),
  manufacturer varchar(100),
  operating_system varchar(100),
  os_version varchar(50),
  browser varchar(100),
  browser_version varchar(50),
  screen_resolution varchar(50),
  registration_date timestamp DEFAULT (CURRENT_TIMESTAMP),
  last_used_at timestamp
);

CREATE TABLE view_history (
  view_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  film_id integer NOT NULL,
  device_id integer NOT NULL,
  viewed_at timestamp DEFAULT (CURRENT_TIMESTAMP),
  view_duration integer,
  view_percent decimal(5,2),
  ip_address varchar(50)
);

CREATE TABLE review (
  review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer NOT NULL,
  user_id integer NOT NULL,
  review_text text NOT NULL,
  film_rating integer,
  likes_count integer DEFAULT 0,
  dislikes_count integer DEFAULT 0,
  created_at timestamp DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamp
);

CREATE TABLE review_rating (
  review_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id integer NOT NULL,
  user_id integer NOT NULL,
  rating_type varchar(50) NOT NULL,
  rated_at timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE critic_review (
  critic_review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer NOT NULL,
  person_id integer NOT NULL,
  publication_name varchar(255),
  title varchar(500),
  review_text text NOT NULL,
  summary text,
  rating decimal(3,1),
  published_at date,
  source_url varchar(1000),
  views_count integer DEFAULT 0
);

CREATE TABLE festival (
  festival_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) UNIQUE NOT NULL,
  country_id integer,
  city_id integer,
  founded_year integer,
  description text,
  prestige_rating decimal(3,2)
);

CREATE TABLE award (
  award_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  festival_id integer NOT NULL,
  year integer NOT NULL,
  film_id integer,
  person_id integer,
  category varchar(255),
  person_role varchar(100),
  status varchar(50) NOT NULL,
  description text
);

CREATE TABLE user_preference (
  preference_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  genre_id integer,
  film_id integer,
  preference_type varchar(50) NOT NULL,
  added_at timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- Индексы

CREATE INDEX ON city (country_id);
CREATE UNIQUE INDEX ON city (country_id, name);

CREATE INDEX ON app_user (email);
CREATE INDEX ON app_user (country_id);
CREATE INDEX ON app_user (city_id);
CREATE INDEX ON app_user (registration_date);

CREATE INDEX ON person (first_name, last_name);
CREATE INDEX ON person (country_id);
CREATE INDEX ON person (city_id);
CREATE INDEX ON person (birth_date);

CREATE INDEX ON person_role (person_id);
CREATE INDEX ON person_role (role);
CREATE UNIQUE INDEX ON person_role (person_id, role);

CREATE INDEX ON genre (name);

CREATE INDEX ON film (title);
CREATE INDEX ON film (created_date);
CREATE INDEX ON film (average_rating);

CREATE INDEX ON film_genre (film_id);
CREATE INDEX ON film_genre (genre_id);
CREATE UNIQUE INDEX ON film_genre (film_id, genre_id);

CREATE INDEX ON film_person (film_id);
CREATE INDEX ON film_person (person_id);
CREATE INDEX ON film_person (role);
CREATE UNIQUE INDEX ON film_person (film_id, person_id, role);

CREATE INDEX ON user_device (user_id);
CREATE INDEX ON user_device (type);

CREATE INDEX ON view_history (user_id);
CREATE INDEX ON view_history (film_id);
CREATE INDEX ON view_history (device_id);
CREATE INDEX ON view_history (viewed_at);

CREATE INDEX ON review (film_id);
CREATE INDEX ON review (user_id);
CREATE INDEX ON review (created_at);

CREATE INDEX ON review_rating (review_id);
CREATE INDEX ON review_rating (user_id);
CREATE UNIQUE INDEX ON review_rating (review_id, user_id);

CREATE INDEX ON critic_review (film_id);
CREATE INDEX ON critic_review (person_id);
CREATE INDEX ON critic_review (published_at);

CREATE INDEX ON festival (country_id);
CREATE INDEX ON festival (city_id);
CREATE INDEX ON festival (name);
CREATE INDEX ON festival (prestige_rating);

CREATE INDEX ON award (festival_id);
CREATE INDEX ON award (film_id);
CREATE INDEX ON award (person_id);
CREATE INDEX ON award (year);

CREATE INDEX ON user_preference (user_id);
CREATE INDEX ON user_preference (genre_id);
CREATE INDEX ON user_preference (film_id);
CREATE INDEX ON user_preference (preference_type);

-- Внешние ключи

ALTER TABLE city ADD FOREIGN KEY (country_id) REFERENCES country (country_id);

ALTER TABLE app_user ADD FOREIGN KEY (country_id) REFERENCES country (country_id);
ALTER TABLE app_user ADD FOREIGN KEY (city_id) REFERENCES city (city_id);

ALTER TABLE person ADD FOREIGN KEY (country_id) REFERENCES country (country_id);
ALTER TABLE person ADD FOREIGN KEY (city_id) REFERENCES city (city_id);

ALTER TABLE festival ADD FOREIGN KEY (country_id) REFERENCES country (country_id);
ALTER TABLE festival ADD FOREIGN KEY (city_id) REFERENCES city (city_id);

ALTER TABLE person_role ADD FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE film_person ADD FOREIGN KEY (person_id) REFERENCES person (person_id);
ALTER TABLE critic_review ADD FOREIGN KEY (person_id) REFERENCES person (person_id);
ALTER TABLE award ADD FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES film (film_id);
ALTER TABLE film_person ADD FOREIGN KEY (film_id) REFERENCES film (film_id);
ALTER TABLE view_history ADD FOREIGN KEY (film_id) REFERENCES film (film_id);
ALTER TABLE review ADD FOREIGN KEY (film_id) REFERENCES film (film_id);
ALTER TABLE critic_review ADD FOREIGN KEY (film_id) REFERENCES film (film_id);
ALTER TABLE award ADD FOREIGN KEY (film_id) REFERENCES film (film_id);
ALTER TABLE user_preference ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id);
ALTER TABLE user_preference ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id);

ALTER TABLE user_device ADD FOREIGN KEY (user_id) REFERENCES app_user (user_id);
ALTER TABLE view_history ADD FOREIGN KEY (user_id) REFERENCES app_user (user_id);
ALTER TABLE review ADD FOREIGN KEY (user_id) REFERENCES app_user (user_id);
ALTER TABLE review_rating ADD FOREIGN KEY (user_id) REFERENCES app_user (user_id);
ALTER TABLE user_preference ADD FOREIGN KEY (user_id) REFERENCES app_user (user_id);

ALTER TABLE view_history ADD FOREIGN KEY (device_id) REFERENCES user_device (device_id);

ALTER TABLE review_rating ADD FOREIGN KEY (review_id) REFERENCES review (review_id);

ALTER TABLE award ADD FOREIGN KEY (festival_id) REFERENCES festival (festival_id);
CREATE TABLE role (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  description text
);

CREATE TABLE permission (
  permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action varchar(50) NOT NULL,
  resource varchar(100) NOT NULL,
  description text,
  UNIQUE (action, resource)
);

CREATE TABLE role_permission (
  role_id integer NOT NULL,
  permission_id integer NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  FOREIGN KEY (role_id) REFERENCES role (role_id),
  FOREIGN KEY (permission_id) REFERENCES permission (permission_id)
);

CREATE TABLE user_role (
  user_id integer NOT NULL,
  role_id integer NOT NULL,
  assigned_at timestamp DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES app_user (user_id),
  FOREIGN KEY (role_id) REFERENCES role (role_id)
);

CREATE INDEX ON user_role (user_id);
CREATE INDEX ON user_role (role_id);

CREATE INDEX ON role_permission (role_id);
CREATE INDEX ON role_permission (permission_id);


INSERT INTO role (name, description) VALUES
  ('user', 'Registered user'),
  ('moderator', 'Content moderator'),
  ('content_editor', 'Content editor'),
  ('admin', 'System administrator');

INSERT INTO permission (action, resource, description) VALUES
  -- Фильмы
  ('read',   'film', 'View films and basic info'),
  ('create', 'film', 'Create films'),
  ('update', 'film', 'Update films'),
  ('delete', 'film', 'Delete films'),

  -- Отзывы
  ('read',   'review', 'Read reviews'),
  ('create', 'review', 'Create reviews'),
  ('update', 'review_own', 'Update own reviews'),
  ('delete', 'review_own', 'Delete own reviews'),
  ('moderate', 'review', 'Moderate any review'),

  -- Оценки отзывов
  ('create', 'review_rating', 'Rate reviews'),
  ('delete', 'review_rating', 'Remove ratings'),

  -- Предпочтения пользователя
  ('manage', 'user_preference', 'Manage own preferences'),

  -- Персоны
  ('read',   'person', 'View persons'),
  ('create', 'person', 'Create persons'),
  ('update', 'person', 'Update persons'),
  ('delete', 'person', 'Delete persons'),

  -- Фестивали и награды
  ('read',   'festival', 'View festivals'),
  ('create', 'festival', 'Create festivals'),
  ('update', 'festival', 'Update festivals'),
  ('delete', 'festival', 'Delete festivals'),

  ('read',   'award', 'View awards'),
  ('create', 'award', 'Create awards'),
  ('update', 'award', 'Update awards'),
  ('delete', 'award', 'Delete awards'),

  -- Связи фильм‑жанр и фильм‑персона
  ('manage', 'film_genre', 'Manage film-genre relations'),
  ('manage', 'film_person', 'Manage film-person relations'),

  -- Профиль пользователя
  ('read',   'user_profile', 'Read own profile'),
  ('update', 'user_profile', 'Update own profile'),
  ('manage', 'user', 'Manage users (admin)'),
  ('manage', 'role', 'Manage roles and assignments');

-- user
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r
JOIN permission p
  ON (
    (r.name = 'user' AND p.action = 'read'   AND p.resource IN ('film', 'review', 'person', 'festival', 'award'))
 OR (r.name = 'user' AND p.action = 'create' AND p.resource IN ('review', 'review_rating'))
 OR (r.name = 'user' AND p.action = 'update' AND p.resource IN ('review_own', 'user_profile'))
 OR (r.name = 'user' AND p.action = 'delete' AND p.resource IN ('review_own'))
 OR (r.name = 'user' AND p.action = 'manage' AND p.resource IN ('user_preference'))
 OR (r.name = 'user' AND p.action = 'read'   AND p.resource = 'user_profile')
  );

-- moderator
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r
JOIN permission p
  ON r.name = 'moderator'
 AND (
    (p.action = 'read'    AND p.resource IN ('film', 'review', 'person', 'festival', 'award', 'user_profile'))
 OR (p.action = 'moderate' AND p.resource = 'review')
 OR (p.action = 'delete'   AND p.resource = 'review')
 OR (p.action = 'delete'   AND p.resource = 'review_rating')
  );

-- content_editor
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r
JOIN permission p
  ON r.name = 'content_editor'
 AND (
    (p.action IN ('read','create','update','delete') AND p.resource IN ('film','person','festival','award'))
 OR (p.action = 'manage' AND p.resource IN ('film_genre','film_person'))
  );

-- admin — получает все permissions
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r CROSS JOIN permission p
WHERE r.name = 'admin';
